main:
    path: /
    controller: App\Controller\MainPageController::redir
content:
    path: /content
    controller: App\Controller\ContentController::index
part_create:
    path: aircrafts/add_part/{id}
    controller: App\Controller\PartsController::create
part_info:
    path: aircrafts/parts/{id}
    controller: App\Controller\PartsController::info
part_delete:
    path: aircrafts/parts/delete/{id}
    controller: App\Controller\PartsController::delete
eng_create:
    path: aircrafts/add_eng/{id}
    controller: App\Controller\PartsController::createEng
users:
    path: /users
    controller: App\Controller\UsersController::index
user:
    path: /users/{id}
    controller: App\Controller\UsersController::get
user_delete:
    path: /users/delete/{id}
    controller: App\Controller\UsersController::delete
userCreate:
    path: /user/create
    controller: App\Controller\UsersController::create
userlogsdel:
    path: /userlogs/delete/{id}
    controller: App\Controller\UsersController::delLogs

content_edit:
    path: /content/edit/{page}
    controller: App\Controller\ContentController::edit

page:
    path: /page/{page}
    controller: App\Controller\ContentController::getContent

authtorization:    
    path: /login
    controller: App\Controller\EmployeesPageController::auth
    

employees_page:
    path: /employees
    controller: App\Controller\EmployeesPageController::index

exit:
    path: /exit
    controller: App\Controller\ExitController::index

aircrafts_page:
    path: /aircrafts
    controller: App\Controller\AircraftController::index    
add_ac_type:
    path: /add_ac_type
    controller: App\Controller\AcTypesController::create
download:
    path: /aircrafts/download/{id}/{fileName}
    controller: App\Controller\AircraftController::testWord

aircraft_create:
    path: /aircrafts/create
    controller: App\Controller\AircraftController::create

aircraft_edit:
    path: /aircrafts/edit/{id}
    controller: App\Controller\AircraftController::edit
aircraft_info:
    path: /aircrafts/{id}
    controller: App\Controller\AircraftController::info

aircraft_delete:
    path: /aircrafts/delete/{id}
    controller: App\Controller\AircraftController::delete    
